#!/bin/sh

. EXECUTABLES/config.sh

# SURVEY can be from ZTF LSST

SURVEY=$1

OBSERVING_WINDOW_VAR="OBSERVING_WINDOW_TDE_${SURVEY}"
OBSERVING_WINDOW=$(eval echo \$$OBSERVING_WINDOW_VAR)

BANDS_VAR="BANDS_${SURVEY}"
BANDS=$(eval echo \$$BANDS_VAR)

python eval_TDE_fisher.py \
  --OBSERVING_WINDOW "$OBSERVING_WINDOW" \
  --SURVEY "$SURVEY" \
  --BANDS $BANDS \
  --NPROC 10 \
  --PLOT_CORNER False \
  --PLOT_FISHER False \
  --PLOT_COVARIANCE False \
  --PLOT_HISTOGRAMS False 