#!/bin/sh

. EXECUTABLES/config.sh

MIN_DETECTIONS=0

for SURVEY in ZTF LSST
do
  OBSERVING_WINDOW_VAR="OBSERVING_WINDOW_TDE_${SURVEY}"
  OBSERVING_WINDOW=$(eval echo \$$OBSERVING_WINDOW_VAR)
  
  BANDS_VAR="BANDS_${SURVEY}"
  BANDS=$(eval echo \$$BANDS_VAR)

  python calculate_SNR_TDE.py \
    --OBSERVING_WINDOW "$OBSERVING_WINDOW" \
    --MIN_DETECTIONS "$MIN_DETECTIONS" \
    --SURVEY "$SURVEY" \
    --BANDS $BANDS
done