#!/bin/sh

. EXECUTABLES/config.sh

OBSERVING_WINDOW=$OBSERVING_WINDOW_TDE # this is in days
MIN_DETECTIONS=2

python calculate_SNR_TDE.py --OBSERVING_WINDOW $OBSERVING_WINDOW --MIN_DETECTIONS $MIN_DETECTIONS